google_cloud:
  credentials_json_file: ""
  vertex_ai_location: "training_job_location"

vertex_ai:
  location: "training job location. It cannot be multi-regional"
  repository: "repository name in Artifact Registry where the image is going to be located"
  image: "name to give to the training Docker image"
  serving_pre_built_container: 'serving_pre_built_container_image'
  # https://cloud.google.com/vertex-ai/docs/training/pre-built-containers
  # https://cloud.google.com/vertex-ai/docs/predictions/pre-built-containers

google_gcs:
  bucket_name: "storage_bucket_name"
  directory_name: "storage_folder_name"

local_dir_path: "to_local_directory"

project_name: "bq_project_name"
dataset_name: "bq_dataset_name"